env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*  
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-ec2connect
    homepage:  https://github.com/hupe1980/ec2connect
    description: ec2connect is an interactive CLI tool that you can use to connect to your EC2 instances using the AWS Systems Manager Session Manager
    license: MIT
    test: |
      system "#{bin}/ec2connect -v"
    install: |-
      bin.install "ec2connect"
      bash_completion.install "completions/ec2connect.bash" => "ec2connect"
      zsh_completion.install "completions/ec2connect.zsh" => "_ec2connect"
      fish_completion.install "completions/ec2connect.fish"
scoop:
  bucket:
    owner: hupe1980
    name: ec2connect-bucket
  homepage:  https://github.com/hupe1980/ec2connect
  description: ec2connect is an interactive CLI tool that you can use to connect to your EC2 instances using the AWS Systems Manager Session Manager
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/ec2connect
    description: ec2connect is an interactive CLI tool that you can use to connect to your EC2 instances using the AWS Systems Manager Session Manager
    license: MIT
    contents:
      - src: ./completions/ec2connect.bash
        dst: /etc/bash_completion.d/ec2connect
      - src: ./completions/ec2connect.fish
        dst: /usr/share/fish/completions/ec2connect.fish
      - src: ./completions/ec2connect.zsh
        dst: /usr/local/share/zsh/site-functions/_ec2connect
    formats:
    - apk
    - deb
    - rpm
