env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*  
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: hupe1980
      name: homebrew-awsconnect
    homepage:  https://github.com/hupe1980/awsconnect
    description: awsconnect is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
    license: MIT
    test: |
      system "#{bin}/awsconnect -v"
    install: |-
      bin.install "awsconnect"
      bash_completion.install "completions/awsconnect.bash" => "awsconnect"
      zsh_completion.install "completions/awsconnect.zsh" => "_awsconnect"
      fish_completion.install "completions/awsconnect.fish"
scoop:
  bucket:
    owner: hupe1980
    name: awsconnect-bucket
  homepage:  https://github.com/hupe1980/awsconnect
  description: awsconnect is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/hupe1980/awsconnect
    description: awsconnect is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager
    license: MIT
    contents:
      - src: ./completions/awsconnect.bash
        dst: /etc/bash_completion.d/awsconnect
      - src: ./completions/awsconnect.fish
        dst: /usr/share/fish/completions/awsconnect.fish
      - src: ./completions/awsconnect.zsh
        dst: /usr/local/share/zsh/site-functions/_awsconnect
    formats:
    - apk
    - deb
    - rpm
